apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-device-pvc
spec:
  storageClassName: {{ .Values.database.volume.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
