apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: default
spec:
  containers:
  - name: mysql
    image: nginx
    env:
    - name: MYSQL_ROOT_PASSWORD
      valuesFrom:
        secretkeyRef:
          name: mysql
          key: password
