apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  storageClassName: {{ .Values.database.volume.storageClassName }}
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

